### ISSUE TITLE
Text says 'OK will ask you to identify yourself', when it does not

### ISSUE THREAD

**Issue by yuvipanda** [data-8/materials-x18#2]
In lab01, it says:

> All assignments in the course will be distributed as notebooks like this one, and you will submit your work from the notebook. We will use a system called OK that checks your work and helps you submit. At the top of each assignment, you'll see a cell like the one below that prompts you to identify yourself. Run it to import your autograder tests.

We don't actually ask users to identify themselves, so this is confusing and should be fixed.

**Comment by wiltonwu** [comment]
Yup just changed it, thanks for catching that!
