### ISSUE TITLE
Fix explanation of how grading is going to work

### ISSUE THREAD

**Issue by yuvipanda** [data-8/materials-x18#3]
In lab01, the last cell says 'run this cell to submit your lab'. This is not true - we look for the file only after the deadline passes. It's critical to explain this to the students, so they don't leave their notebook in an incorrect state believing that they've already 'submitted' it.

**Comment by wiltonwu** [comment]
Okay, I will clarify in all the labs.

**Comment by wiltonwu** [comment]
Okay should be fixed now!
