### ISSUE TITLE
Don't fetch data from data8.org

### ISSUE THREAD

**Issue by yuvipanda** [data-8/materials-x18#5]
For security reasons, we whitelist domains that we allow outgoing connections for. This requires that the website be accessible through https.

https://www.inferentialthinking.com/ is accessible via https, but data8.org is not. I see in lecture 01 that it's using the link to data8.org. Instead, it should be using the link via inferentialthinking.com (https://www.inferentialthinking.com/chapters/01/3/little_women.txt). Similar for other locations.

Am happy to whitelist more domains!

/cc @papajohn @wiltonwu

**Comment by papajohn** [comment]
Fixed
